;	DME assembly file, generated by lcc 4.2

;  temp boiler plate puts SP at 0x64 and branches to main
	ld16	r1, 0x1ffe
	mov	sp, r1
	addi	r1, pc, 2
	br	_main
	hlt


;	.global _fib
;	.cseg
_fib:
	push	r1
	push	bp
	mov	bp, sp
	ldi	r4, 2
	sub	sp, sp, r4
	ldw	r4,4(bp)
	ldi	r3, 2
	skip.lt r4, r3
	br L2
	ldw	r1,4(bp)
	la16	r4,L1 ;[via BASE][BASE]
	br.r r4
L2:
	ldw	r4,4(bp)
	subi	r4,r4,1
	push	r4
	addi	r1,pc,2
	br	_fib ;XX
	mov	r4,r1
	stw	-2(bp),r4
	ldw	r3,4(bp)
	subi	r3,r3,2
	push	r3
	addi	r1,pc,2
	br	_fib ;XX
	mov	r4,r1
	ldw	r3,-2(bp)
	add	r1,r3,r4
L1:
	mov	sp, bp
	pop	bp
	pop	pc

;	.global _main
_main:
	push	r1
	push	bp
	mov	bp, sp
	ldi	r4, 2
	sub	sp, sp, r4
	stw	-2(bp),r0
	ldi	r4, 10
	push	r4
	addi	r1,pc,2
	br	_fib ;XX
	mov	r4,r1
L4:
	mov	sp, bp
	pop	bp
	pop	pc

;	.end
