;	DME assembly file, generated by lcc 4.2

;  temp boiler plate puts SP at 0x2000 and branches to main
	ld16	r1, 0x2000
	mov	sp, r1
	addi	r1, pc, 2
	br	_main
	hlt


;	.global _func
;	.code
_func:
	push	r1
	push	bp
	mov	bp, sp
	ldi	r4, 4
	sub	sp, sp, r4
	ld16	r4, 2
	stw	-2(bp),r4
	ld16	r4, 3
	ldw	r3,-2(bp)
mul $r4,$r4,$r3
	stw	-4(bp),r4
L1:
	mov	sp, bp
	pop	bp
	pop	pc

;	.end
