;	DME assembly file, generated by lcc 4.2

;  temp boiler plate puts SP at 0x64 and branches to main
	ld16	r1, 0x1ffe
	mov	sp, r1
	br	_main


	.data 0x1000
;	.global _result
_result:
	defw 0x0
;	.global _foo
;	.cseg
_foo:
	push	r1
	push	bp
	mov	bp, sp
	ldi	r4, 2
	sub	sp, sp, r4
	ldw	r4,4(bp)
	addi	r4,r4,4
	stw	-2(bp),r4
	ldw	r1,-2(bp)
L1:
	mov	sp, bp
	pop	bp
	pop	pc

;	.global _main
_main:
	push	r1
	push	bp
	mov	bp, sp
	ldi	r4, 2
	sub	sp, sp, r4
	ldi	r4, 2
	push	r4
	addi	r1,pc,4
	br	_foo ;XX
	stw	-2(bp),r1
	ldw	r4,-2(bp)
	addi	r4,r4,1
	stw	-2(bp),r4
	la16	r4,_result ;[via BASE][BASE]
	ldw	r3,-2(bp)
	stw	r0(r4),r3
	ldi	r0, 0
	mov	r1,r0
L2:
	mov	sp, bp
	pop	bp
	pop	pc

;	.end
